spring.config.import=optional:file:.env[.properties]
spring.application.name=sideru-backend
server.port=8080
spring.output.ansi.enabled=ALWAYS
server.servlet.context-path=/api
springdoc.swagger-ui.path=/docs
springdoc.openapi.info.title=Sideru API
# spring.profiles.active=

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
# Show and format sql queries on the logs
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect